Add referral tracking to button
usdigitalresponse/la-health-work-connect pull request #11
Opened 2020-05-12 22:46 UTC by curiousjazz77

Updated to be in line with that article, you sent Peter: https://flaviocopes.com/nextjs-server-client-code/

Moves forward our Airtable JIRA card: https://airtable.com/tblJy1oiCbCLjpTMr/viwV0wMqhSBakeaKS/recfkyNojgkqOyHLX
@pjstein

2020-05-12 22:50 UTC, curiousjazz77 commented
Note: troubleshooting the page error

2020-05-13 16:21 UTC, pjstein requested changes

2020-05-13 16:21 UTC, pjstein commented on pages/index.js
> +  const REFERRAL = typeof window !== 'undefined' ? `?prefill_Source=${encodeURIComponent(location.search)}` : "?prefill_Source=Louisiana%20Health%20Work%20Connect%20Website";
You want to extract the `source` parameter from the query string and use that as the `prefill_Source` parameter in the URL you're manufacturing. 

Right now, if say `https://healthworkconnect.la.gov/?this=is&a=test` is the URL, then `window.location.search` is `"?this=is&a=test"` and that is the value that will wind up prefilled in source. That won't be super useful on the backend.

2020-05-13 16:21 UTC, pjstein commented on pages/index.js
> +// const what = withRouter.query;
Delete.

2020-05-14 17:08 UTC, curiousjazz77 commented
last tested: https://la-health-work-connect-i7g1535n9.now.sh/?utm_campaign=dealofday&utm_source=linkedin&utm_medium=social-media

and 

https://la-health-work-connect-i7g1535n9.now.sh/?no_sourcing_added_test
https://la-health-work-connect-i7g1535n9.now.sh/?

2020-05-15 13:45 UTC, pjstein approved these changes

2020-05-15 13:52 UTC, merged